# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shittie Breaking Coding Jam
tagline:          'Anther Computer Science & Design Blog'
description:      'A Blog run by Shittie and Wolfie.'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aileen Xi'
  url:            https://www.instagram.com/thatwolfiefeeling/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/notagenius/notagenius.github.io
