# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Not a Genius
tagline:          'Science & Design Blog'
description:      'Blog of Weiling.'
url:              http://notagenius.rocks
baseurl:          /

author:
  name:           'Aileen Xi'
  url:            https://www.instagram.com/thatwolfiefeeling/

paginate:         5

# Custom vars
version:          0.0.9

github:
  repo:           https://github.com/notagenius/notagenius.github.io
